# Generated by Django 5.0.2 on 2024-02-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
